stages:
  - test
  - publish

test:
  stage: test
  tags: ["python3.10"]
  script:
    - python3.10 -m venv venv
    - source venv/bin/activate
    - pip3.10 install -e .
    - pip3.10 install pytest pytest-cov
    - python3.10 -m pytest --cov=src --cov-report=term-missing --cov-fail-under=80 --capture=no
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH =~ /^release.*/'
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+.*$/'

pulish:
  stage: publish
  needs: ["test"]
  tags: ["python3.10"]
  script:
    - python3.10 -m venv venv
    - source venv/bin/activate
    - pip3.10 install uv
    - uv build
    - uv publish --token "$PYPI_TOKEN"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+.*$/'

